name: Deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: echo "npm ci"
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "npm run deploy"
